### ISSUE TITLE
Sniper crashes when it has to snipe

### ISSUE THREAD

**Issue by Microck** [snipesmarter/smart-sniper#16]
I put all the info, etc and when is supposed to snipe it just crashes/closes?

**Comment by coolkidmacho** [comment]
Use cmd as listed in the instructions, send the error here

**Comment by Microck** [comment]
it just crashes, I used cmd as the instructiosn said. no error unless they save in a logs.txt I dont know about

**Comment by coolkidmacho** [comment]
cmd would show a error if it crashes the window would not close
