### ISSUE TITLE
How do I tell what time the sniper is sniping at

### ISSUE THREAD

**Issue by Ihavenoiqq** [snipesmarter/smart-sniper#18]
I was wondering how to tell what time it is sniping at because it seems to me like a bunch of somewhat random numbers.

**Comment by EBSmash** [comment]
is will say "Sniping (Name) at (timestamp)". copy the timestamp and paste it into [](https://www.epochconverter.com/) it will give you a time you will undersstand 
ex: [](https://among-us-in-real.life/nrWajfWz)
